

CREATE TABLE CLIENT(
RefC INT NOT NULL,
NomC VARCHAR(10) NOT NULL,
Ville VARCHAR(10) NOT NULL,
CAT INT NOT NULL,
PRIMARY KEY (RefC)
);

CREATE table PRODUIT(
RefP VARCHAR(10) NOT NULL,
TypeP VARCHAR(10) NOT NULL,
Prix INT NOT NULL,
QStock INT NOT NULL,
PRIMARY KEY (RefP)
);

CREATE TABLE COMMANDE(
RefCom VARCHAR(10) NOT NULL,
RefC VARCHAR NOT NULL(10),
DateCom VARCHAR NOT NULL(10),
PRIMARY KEY (RefC)
);

CREATE TABLE DETAIL(
RefP VARCHAR(10) NOT NULL,
RefCom VARCHAR(10) NOT NULL,
Quantite INT NOT NULL,
PRIMARY KEY (RefCom,RefP)
);


LOAD DATA LOCAL INFILE "client.dat" INTO TABLE CLIENT;
LOAD DATA LOCAL INFILE "produit.dat" INTO TABLE PRODUIT;
LOAD DATA LOCAL INFILE "commande.dat" INTO TABLE COMMANDE;
LOAD DATA LOCAL INFILE "detail.dat" INTO TABLE DETAIL;







